# Alias
alias yt-dlp='yt-dlp -q --console-title --no-warnings --progress'
alias nini='loginctl suspend'
alias off='loginctl poweroff'
alias img='xrdb /home/chocotux/.Xresources & urxvt'
alias cl='clear'
alias bs='vi ~/.bashrc'
alias l='ls -al'
alias ex='exit'
alias hl='cat ~/Downloads/main/gentoo_useFullCommand.md'
alias ihl='vi ~/Downloads/main/gentoo_useFullCommand.md'
alias postman='~/Downloads/main/executable/Postman/Postman'
alias obsidian='~/Downloads/main/executable/Obsidian-1.6.7.AppImage'
alias nd='cd ~/Downloads/writing/nodejs'
alias py='cd ~/Downloads/writing/python'
alias main='cd Downloads/main'
alias iswr='doas isw -w 16R3EMS1'
alias vid='ranger ~/Downloads/videos'
alias lrust='. ~/.config/localrust.sh'
alias dot='git --git-dir=$HOME/Downloads/writing/dotfiles/ --work-tree=$HOME'
